### ISSUE TITLE
Test: InvalidGetSourceModule_NoModule_Test cannot be successful

### ISSUE THREAD

**Issue by InfiniteProductions** [rthome/SharpNoise#1]
Using `var source = module.SourceModules[0];` will never thrown the expected exception (`NoModuleException`) as Module class constructor will always initialize source array properly:

```
if (sourceModuleCount > 0)
                sourceModules = new Module[sourceModuleCount];
            else
                sourceModules = emptyModulesArray;
```

(and also, exception is not even declared as throw-able, AFAIK)

**Comment by rthome** [comment]
Thank you! :-)
