### ISSUE TITLE
Support for .Net Core would be nice

### ISSUE THREAD

**Issue by zhulika** [rthome/SharpNoise#16]
I'm not sure if there is anything in the library that couldn't work with .Net Core. especially now that version 2.0 is available. Is it just a matter of adding new targets to the nupkg?

**Comment by rthome** [comment]
Hi,

I believe most or all of the current code works targeting .NET Core/Standard without any changes. You'd need to create a new csproj targeting .Net Standard and create new Nuget targets. It would also be nice to have some automated testing, like I have now with Travis and AppVeyor.

If you (or anyone else) would be willing to do that work, I'd be happy to accept it :)

**Comment by zhulika** [comment]
oops. the dog clicked the wrong button
