### ISSUE TITLE
Cubic interpolation bug

### ISSUE THREAD

**Issue by zirik** [rthome/SharpNoise#18]
I was getting weird results from the Curve module so I went digging through the code.
This is the return statement from the CubicInterp function in the original libnoise:
`return p * a * a * a + q * a * a + r * a + s;`
And this is the return statement from the Cubic method of NoiseMath in SharpNoise:
`return (p * a * a * a) + (q * a * a * a) + (r * a) + s;`
It seems `q` is being multiplied by `a` one too many times. Removing the extra multiplication fixed the issues I was having.

**Comment by rthome** [comment]
Thanks - this will be fixed in the next release. Whenever that is...
