### ISSUE TITLE
Spheres Module doesnt works at all

### ISSUE THREAD

**Issue by artrevinho** [rthome/SharpNoise#22]
Hello , first say thanks for this nice library is pretty interesting and useful, im doing a visual implementation for a programming enviroment call vvvv gamma,i get all the modules work except the spheres, is implemented in the library or just on the way?
Thanks

**Comment by rthome** [comment]
It's definitely supposed to work. I'll take a look as soon as I can.

**Comment by rthome** [comment]
This is fixed in the latest master. Sorry about the wait.

**Comment by artrevinho** [comment]
Hi raffael thanks for your answer, actually testing latest release, found
that the new spheres implementation is the same as cylinders, so actually
is not working correctly, please check it
regards

**Comment by rthome** [comment]
Seems to me like both modules work as intended. One produces concentric cylinders, the other produces concentric spheres around the origin. Think rings of a tree vs rings of an onion.
What's wrong with the implementation, in your opinion?
